import { CryptoJS as C } from './core.js';
export const CryptoJS = C;

import { OpenSSLKdf } from './openssl-key-derivation-function.js';
import { AES } from './aes.js';
import { Blowfish } from './blowfish.js';
import { Base64 } from './enc-base64.js';
import { Base64url } from './enc-base64url.js';
import { Utf16BE, Utf16LE } from './enc-utf16.js';
import { HexFormatter } from './format-hex.js';
import { HMAC } from './hmac.js';
import { MD5 } from './md5.js';
import { CFB } from './mode-cfb.js';
import { CTRGladman } from './mode-ctr-gladman.js';
import { CTR } from './mode-ctr.js';
import { ECB } from './mode-ecb.js';
import { OFB } from './mode-ofb.js';
import { AnsiX923 } from './pad-ansix923.js';
import { Iso10126 } from './pad-iso10126.js';
import { Iso97971 } from './pad-iso97971.js';
import { NoPadding } from './pad-nopadding.js';
import { ZeroPadding } from './pad-zeropadding.js';
import { PBKDF2 } from './pbkdf2.js';
import { RabbitLegacy } from './rabbit-legacy.js';
import { Rabbit } from './rabbit.js';
import { RC4, RC4Drop } from './rc4.js';
import { RIPEMD160 } from './ripemd160.js';
import { SHA1 } from './sha1.js';
import { SHA3 } from './sha3.js';
import { SHA224 } from './sha224.js';
import { SHA256 } from './sha256.js';
import { SHA384 } from './sha384.js';
import { SHA512 } from './sha512.js';
import { DES, TripleDES } from './tripledes.js';
import { X64Word, X64WordArray } from './x64-core.js';
import { EvpKDF } from './evpkdf.js';
EvpKDF.defaultConf.hasher = MD5;
OpenSSLKdf.EvpKDF = EvpKDF;
C.algo.AES = AES;
C.algo.Blowfish = Blowfish;
C.enc.Base64 = Base64;
C.enc.Base64url = Base64url;
C.enc.Utf16 = Utf16BE; // Alias for UTF-16 BE
C.enc.Utf16BE = Utf16BE; // Alias for UTF-16 BE
C.enc.Utf16LE = Utf16LE;
C.algo.EvpKDF = EvpKDF;
C.format.Hex = HexFormatter;
C.algo.HMAC = HMAC;
C.algo.MD5 = MD5;
C.mode.CFB = CFB;
C.mode.CTRGladman = CTRGladman;
C.mode.CTR = CTR;
C.mode.ECB = ECB;
C.mode.OFB = OFB;
C.pad.AnsiX923 = AnsiX923;
C.pad.Iso10126 = Iso10126;
C.pad.Iso97971 = Iso97971;
C.pad.NoPadding = NoPadding;
C.pad.ZeroPadding = ZeroPadding;
C.algo.PBKDF2 = PBKDF2;
C.algo.RabbitLegacy = RabbitLegacy;
C.algo.Rabbit = Rabbit;
C.algo.RC4 = RC4;
C.algo.RC4Drop = RC4Drop;
C.algo.RIPEMD160 = RIPEMD160;
C.algo.SHA1 = SHA1;
C.algo.SHA3 = SHA3;
C.algo.SHA224 = SHA224;
C.algo.SHA256 = SHA256;
C.algo.SHA384 = SHA384;
C.algo.SHA512 = SHA512;
C.algo.DES = DES;
C.algo.TripleDES = TripleDES;
C.x64.Word = X64Word;
C.x64.WordArray = X64WordArray;
